# Services
services:

  # Testimony Service
  webcast-app:
    container_name: webcast-app
    image: dclm/dclm-webcast
    ports:
      - 5000:80
    networks:
      - webcast
    #volumes:
      #- ./:/var/www/html
      #- ./.docker/testify.conf:/etc/nginx/sites-available/default.conf
      # - ./.env:/var/www/html/.env
    restart: always

networks:
  webcast:
    name: webcast-app