apiVersion: apps/v1
kind: Deployment
metadata:
  name: webcast-app
spec:
  selector:
    matchLabels:
      app: webcast-app
  template:
    metadata:
      labels:
        app: webcast-app
    spec:
      nodeName: bams
      containers:
      - name: webcast-app
        image: dclm/dclm-webcast:${BUILD_NUMBER}
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: webcast-app
spec:
  type: NodePort
  selector:
    app: webcast-app
  ports:
  - port: 80
    targetPort: 3000
